### ISSUE TITLE
how to use spine, if any spine-sparrow runtimes?

### ISSUE THREAD

**Issue by RongjieChen** [Gamua/Sparrow-Framework#43]
just  i   use   sparrow , it's  good.  but i want to   use  http://zh.esotericsoftware.com/   Skeletal animation, please  help  me   to  find  spine-sparrow runtimes?  thx

**Comment by PrimaryFeather** [comment]
As far as I know, there is no Spine runtime for Sparrow at the moment. Sorry!
As an alternative, I can recommend "Flump", though: https://github.com/threerings/flump
That allows you to convert animations created in Adobe Flash for Sparrow.
