### ISSUE TITLE
SPSprite3D scaleX, scaleY, scaleZ properties do not work

### ISSUE THREAD

**Issue by cburtbrown** [Gamua/Sparrow-Framework#55]
In SPSprite3D.m (line 169) the code to apply scaling properties reads:

    if (scaleX != 1.0f || scaleY != 1.0f || _scaleZ != 1.0f)
        [_transformationMatrix3D appendScaleX:scaleX != 0.0f ?: E y:scaleY != 0.0f ?: E z:_scaleZ != 0.0f ?: E];

The expression `scaleX != 0.0f ?: E` will always equal 1 unless scaleX is exactly 0. So scale properties never get applied.

I don't want to give a pull request for this since I don't understand the reason for limiting minimum scale to E instead of allowing 0.

**Comment by racarone** [comment]
Yeah thanks for letting me know! As for the E limit, this was a carried over from Starling, I'll have to ask Daniel if this was Starling/Flash specific or otherwise.

**Comment by PrimaryFeather** [comment]
Ah, haha, yes, that's an odd one. You can safely remove this check, Robert. That's just a peculiarity of the AS3 `Matrix3D` class: it actually throws an exception when you scale anything by zero. Yes, it doesn't make much sense and: no, I don't understand it either. :wink:

**Comment by racarone** [comment]
Gotcha, thanks Daniel =)

**Comment by cburtbrown** [comment]
Wonderful, thanks both of you :)
