### ISSUE TITLE
I hate SpriteKit but...

### ISSUE THREAD

**Issue by hobsynth** [Gamua/Sparrow-Framework#58]
I've spent a couple days trying to use SpriteKit and I have to say that I hate it.  I know that, like countless others, I may be biased coming into iOS with a Flash background.  Simple, silly things like there is apparently no way to be notified when an SKNode is added/removed from the stage.  Also, being closed source, I'm worried that I will run up against a deep rooted performance issue and be held at Apple's mercy for a fix.

I've loved using Sparrow and I wish that was smarter and had more time to contribute.  @racarone @PrimaryFeather I know that I'm probably years behind in the discussion here.  You all, I'm sure, have talked about this stuff already but...

1.  Do you think Sparrow compatibility will withstand the next two or three iOS versions?
2.  Has anyone done any performance testing lately between SpriteKit & Sparrow?  A quick google search leads little results.  It feels the same to me.

I hate being "that guy" to ask these types of questions.  I know the answer probably is, "well, you should help out a little and patch Sparrow yourself".  Honestly guys, I'm just not that smart, especially when it comes to all the crazy GPU rendering.

Thanks in advance.

**Comment by PrimaryFeather** [comment]
Hi Chris,
thanks a lot for your comments! You're touching a sore spot, I wish I had had the time to keep Sparrow updated. But with so many developers flocking to SpriteKit, as well as my (much more popular) work on Starling, it just didn't seem to be worth the effort.

> Also, being closed source, I'm worried that I will run up against a deep rooted performance issue and be held at Apple's mercy for a fix.

You're totally right about that; I also always considered that a major advantage of Sparrow. From the games I made for iOS, those that were built with UIKit are a lost case today — so much has changed that updating them for the latest iOS versions would mean a total rewrite. Sparrow based games, on the other hand, still run without issues.

That also answers question (1): the really small number of dependencies of Sparrow doesn't make it that vulnerable to changes on Apple's side. Much (much!) less so than a SpriteKit app, in my opinion.

(2) I can't find the link right now, but I can remember somebody benchmarking it and coming to roughly the same performance. With modern iOS hardware, though, that shouldn't even be a major concern. The first Sparrow games ran on an iPhone 3G! And that was before the automatic batching introduced in Sparrow 2. 

I hope that helps you a little bit in your decision-making process! :smile:

**Comment by racarone** [comment]
Sorry for the late reply! 

Ya it's definitely sad we can't keep up with development... it is hard to justify the time with people flocking to SpriteKit or cross-platform solutions like the wonderful Starling. 

I still monitor the repo though, incase of any real breaking changes made by Apple, but as Daniel said it really doesn't rely too much on Apple's frameworks, so it should be pretty future proof!

**Comment by PrimaryFeather** [comment]
Thanks, Robert!! :smile:

**Comment by hobsynth** [comment]
Thank you so much @PrimaryFeather & @racarone for your feedback here and all your hard work done for the community.
